# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexd" do
  version "1.0.35"

  on_macos do
    on_arm do
      sha256 "ea1c5c75d766d1077fce9d24188e692e7bf808c6497f0bc0ced08bd701f47077"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d671633ae61e5f9e882d7756f35b8540c698df785ba7b32a5dba237dbdf318e2"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "76ae2087e75266b7c19aa4bb84bb03f518f4ff425fd57e9ed244b16894be55eb"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1255b50592a81fdf97d3b81eb80f5eb861d931799f1d8ddcdafdd7a41f2504f7"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_amd64.tar.gz"
    end
  end

  name "vexd"
  desc "Daemon de ejecución para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexd"

  # No zap stanza required
end
