# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexd" do
  version "1.0.32"

  on_macos do
    on_arm do
      sha256 "fa3c31c93be1583320ec5f93d675fdfa942e57935266b068fbc00e8c6090895a"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "afce1146bc05d525eb2a6eec69c2bb01024531fea08a27be7f3e68f6e95a76c7"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "81a5ca9478d078d6e126b327254c077a3a2710cdccca9d0c9fd2735408c64986"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9be01bbf60b5a52326e1f77a16ba1392516e7c1e76089a37e265bc23076749f"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_amd64.tar.gz"
    end
  end

  name "vexd"
  desc "Daemon de ejecución para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexd"

  # No zap stanza required
end
