# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexd" do
  version "1.0.33"

  on_macos do
    on_arm do
      sha256 "9aac223ac5741bdb2e98effc40d28afc992a68b3e42a784d39807cb34b1cae73"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68dad0cdb5fddc937edb000393e0dfd6ef49d9ef7d5ea9bc5598964b2ac901bf"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97ec4e9b19611cf78a0a97821a0948a704448a00b6a5ad0befcd6f56c64a6047"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d1dbc81f75945e7a9111d01a7c4d053c600a0ee81c298eeedfc19fc49c14e8d3"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_amd64.tar.gz"
    end
  end

  name "vexd"
  desc "Daemon de ejecución para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexd"

  # No zap stanza required
end
